# config/packages/html_sanitizer.yaml
framework:
  html_sanitizer:
    sanitizers:
      emailtemplate_content:
        allow_safe_elements: true
        allow_relative_links: true
        allow_elements:
          html: '*'
          head: '*'
          title: '*'
          meta: [ 'charset', 'name', 'content' ]
          link: [ 'href', 'alt', class,'rel', 'type', 'id' ]
          xml: '*'
          style: '*'
          table: '*'
          tr: '*'
          td: '*'
          tbody: '*'
        allow_attributes:
          style: '*'