knp_snappy:
    pdf:
        enabled:    true
        binary:     '/bin/wkhtmltopdf/wkhtmltopdf'
        options:    []
    image:
        enabled:    false
        binary:     ''
        options:    []
