framework:
  rate_limiter:
    username_login:
      policy: token_bucket
      limit: '%login_limit%'
      rate: { interval: '%login_rate_interval%', amount: '%login_rate_amount%' }

services:

  app.login_rate_limiter:
    class: App\Security\RateLimiter\LsLoginRateLimiter
    arguments:
      $usernameRateLimiterFactory: '@limiter.username_login'

security:
  role_hierarchy:
    ROLE_SUPERADMIN: [ ROLE_MANAGE_STRUCTURES, ROLE_MANAGE_USERS, ROLE_MANAGE_TYPES, ROLE_MANAGE_EMAIL_TEMPLATES,
                       ROLE_MANAGE_PARTIES, ROLE_MANAGE_PREFERENCES, ROLE_MANAGE_THEMES, ROLE_MANAGE_SITTINGS,
                       ROLE_MANAGE_CONNECTORS, ROLE_MANAGE_API_USER, ROLE_MANAGE_GDPR, ROLE_MANAGE_CONFIGURATION, ROLE_SHOW_EVENT_LOG ]
    ROLE_GROUP_ADMIN: [ ROLE_MANAGE_STRUCTURES, ROLE_MANAGE_USERS, ROLE_MANAGE_TYPES, ROLE_MANAGE_EMAIL_TEMPLATES,
                        ROLE_MANAGE_PARTIES,ROLE_MANAGE_PREFERENCES, ROLE_MANAGE_THEMES, ROLE_MANAGE_SITTINGS, ROLE_MANAGE_CONNECTORS,
                        ROLE_MANAGE_API_USER, ROLE_MANAGE_GDPR, ROLE_MANAGE_CONFIGURATION, ROLE_SHOW_EVENT_LOG ]
    ROLE_STRUCTURE_ADMIN: [ ROLE_MANAGE_USERS, ROLE_MANAGE_TYPES, ROLE_MANAGE_EMAIL_TEMPLATES, ROLE_MANAGE_PARTIES,
                            ROLE_MANAGE_PREFERENCES, ROLE_MANAGE_THEMES, ROLE_MANAGE_SITTINGS, ROLE_MANAGE_CONNECTORS, ROLE_MANAGE_API_USER,
                            ROLE_MANAGE_GDPR, ROLE_MANAGE_CONFIGURATION, ROLE_SHOW_EVENT_LOG ]
    ROLE_SECRETARY: [ ROLE_MANAGE_SITTINGS, ROLE_MANAGE_PREFERENCES ]

    ROLE_API_STRUCTURE_ADMIN: [ ROLE_API ]


  password_hashers:
    App\Entity\User:
      algorithm: argon2i



  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

    app_connector_provider:
      entity:
        class: App\Entity\ApiUser
        property: token

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api:
      pattern: ^/api/v2
      provider: app_connector_provider
      stateless: true
      custom_authenticators:
        - App\Security\TokenAuthenticator

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticators:
        - App\Security\LoginFormAuthenticator
        - App\Security\MagicLinkAuthenticator
      user_checker: App\Security\UserChecker
      login_throttling:
        limiter: app.login_rate_limiter


      logout:
        path: app_logout
        target: app_login