twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes: ['bootstrap_4_layout.html.twig', 'others/ls-file.html.twig']
  globals:
    version: '%version%'
    breadcrumb: 'others/breadCrumb.html.twig'
    nginx: '%nginx_host%'
