include:
  - project: "libriciel/integration-continue/templates"
    ref: master
    file: '/publish-container-to-registry.yml'

  - project: "libriciel/integration-continue/templates"
    ref:  security-check-1.0.0
    file: 'jobs/security-check/security-check.yml'

  - project: "libriciel/integration-continue/templates"
    ref: publish-compose-to-nexus@0.1.3
    file: '/jobs/publish-compose-to-nexus/publish-compose-to-nexus.yml'



security-check:
  only:
    - master
  allow_failure: true
  variables:
    TRIVY_IMAGE_TIMEOUT: 10m


stages:
  - build
  - build-nocache
  - deploy
  - testWithoutCovering
  - test
  - quality
  - release

variables:
  CONTAINER_IMAGE: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
  REGISTRY_CONTAINER_PATH: /public/citoyens/idelibre
#  CANARY_BRANCH_NAME: 321-test-v4-2-les-elus-n-ont-pas-la-seance-a-disposition-dans-leur-espace-idelibre



build:
  stage: build
  tags:
    - citoyen-shell
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /nocache/
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag ${CONTAINER_IMAGE} --tag $CI_REGISTRY_IMAGE:latest .
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker push ${CONTAINER_IMAGE}
    - docker push $CI_REGISTRY_IMAGE:latest


build-nocache:
  stage: build-nocache
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /nocache/
  tags:
    - citoyen-shell
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --tag ${CONTAINER_IMAGE} --tag $CI_REGISTRY_IMAGE:latest . --no-cache
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker push ${CONTAINER_IMAGE}
    - docker push $CI_REGISTRY_IMAGE:latest

