version: '3.4'

services:
  fpm-idelibre:
    container_name: fpm-idelibre
    image: gitlab.libriciel.fr:4567/libriciel/pole-citoyens/idelibre/idelibre:isactiveConnector

    env_file:
      - .env.docker.local
    volumes:
      #- data-public:/app/public
      - ./public:/app/public
      - data-file:/tmp
      - ./docker-resources/zz-idelibre.conf:/usr/local/etc/php-fpm.d/zz-idelibre.conf
      - ./src:/app/src
      - ./templates:/app/templates
      - ./config:/app/config
      #- ./vendor:/app/vendor

    command: ["/app/docker-resources/initApp.sh"]


  ## il faut partager le /data/workspace entre le node et le fpm sinon on ne peut pas recuperer les fichiers

  node-idelibre:
    container_name: node-idelibre
    #ports:
    #  - 4000:3000
    image: gitlab.libriciel.fr:4567/libriciel/pole-citoyens/idelibre/idelibre-nodejs:main
    volumes:
      - ../idelibre4-nodejs:/app
      - data-file:/tmp
      #- /tmp/docker:/tmp
    env_file:
      #- docker-resources/.env.test
      - .env.docker.local
    command: [ "/app/docker-resources/init.sh" ]


  nginx-idelibre:
    container_name: nginx-idelibre
    image: nginx:1.17
    depends_on:
      - fpm-idelibre
      - node-idelibre
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker-resources/nginx.vhost:/etc/nginx/conf.d/default.conf
      - ./docker-resources/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-resources/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
      #- data-public:/app/public:ro
      - ./public:/app/public

  certbot:
    image: certbot/certbot
    volumes:
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot

  lshorodatage:
    container_name: lshorodatage
    image: gitlab.libriciel.fr:4567/libriciel/pole-citoyens/lshorodatage/lshorodatage:master
    ports:
      - 5000:3000
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=172.17.0.1
      - POSTGRES_DB=lshorodatage
      - POSTGRES_USER=idelibre
      - POSTGRES_PASSWORD=idelibre
      - POSTGRES_PORT=5432
    command: ["/app/docker-resources/init.sh"]




volumes:
  data-public:
  data-file:
