version: '3.8'

services:
  fpm-idelibre:
    container_name: fpm-idelibre
    image: registry.libriciel.fr:443/public/citoyens/idelibre/idelibre:TAG
    depends_on:
      postgres-idelibre:
        condition: service_healthy
    environment:
      - APP_ENV=${APP_ENV:-prod}
      - APP_SECRET=${APP_SECRET:-b64dca717248e387bc88b36d9c485244}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - VERSION=${VERSION:-TAG}
      - PRODUCT_NAME=${PRODUCT_NAME:-idelibre}
      - PRODUCT_EDITOR=${PRODUCT_EDITOR:-libriciel scop}
      - HIDE_LEFT_BANNER_LOGIN=${HIDE_LEFT_BANNER_LOGIN:-false}
      - MAILER_DSN=${MAILER_DSN:-null://localhost}
      - MAILJET_KEY=${MAILJET_KEY:-null}
      - MAILJET_SECRET=${MAILJET_SECRET:-null}
      - EMAIL_FROM=${EMAIL_FROM:-email@service.fr}
      - EMAIL_ALIAS=${EMAIL_ALIAS:-idelibre}
      - MAILER_TYPE=${MAILER_TYPE:-simple}
      - DOCUMENT_MAX_SIZE=${DOCUMENT_MAX_SIZE:-150Mi}
      - DOCUMENT_MAX_COUNT=${DOCUMENT_MAX_COUNT:-300}
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=${PHP_OPCACHE_VALIDATE_TIMESTAMPS:-0}
      - PHP_MAX_FILE_UPLOADS=${PHP_MAX_FILE_UPLOADS:-600}
      - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE:-200M}
      - PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE:-2000M}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-2100M}
      - PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME:-300}
      - PHP_PM_MAX_CHILDREN=${PHP_PM_MAX_CHILDREN:-15}
      - PHP_PM_START_SERVERS=${PHP_PM_START_SERVERS:-3}
      - PHP_PM_MIN_SPARE_SERVERS=${PHP_PM_MIN_SPARE_SERVERS:-2}
      - PHP_PM_MAX_SPARE_SERVERS=${PHP_PM_MAX_SPARE_SERVERS:-4}
      - SENTRY_DSN=${SENTRY_DSN:-null}
      - SALT=${SALT:-saltsaltsalt}
      - PASSPHRASE=${PASSPHRASE:-passphrase}
      - DISABLE_LEFT_BANNER_LOGIN=${DISABLE_LEFT_BANNER_LOGIN:-false}
      - URL=${URL:-idelibre.collectivite.fr}
      - ENTROPY_ADMIN=${ENTROPY_ADMIN:-130}
      - MAXIMUM_SIZE_PDF_ZIP_GENERATION=${MAXIMUM_SIZE_PDF_ZIP_GENERATION:-200000000}
      - LOCK_DSN=${LOCK_DSN:-semaphore}
    volumes:
      - data-public:/app/public
      - /data/files:/data
    command: [ "/app/docker-resources/initApp.sh" ]
    restart: unless-stopped
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.purge.schedule: "0 0 2 * * * "
      ofelia.job-exec.purge.command: "/app/bin/console purge:structures"
      ofelia.job-exec.attendance.schedule: "0 0 8 * * * "
      ofelia.job-exec.attendance.command: "/app/bin/console attendance:notification"

  node-idelibre:
    container_name: node-idelibre
    image: registry.libriciel.fr:443/public/citoyens/idelibre-node/idelibre-node:4.3.0-alpha.1
    depends_on:
      postgres-idelibre:
        condition: service_healthy
    volumes:
      - /data/files:/data
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=${POSTGRES_HOST:-172.17.0.1}
      - TYPEORM_USERNAME=${POSTGRES_USER:-idelibre}
      - TYPEORM_PASSWORD=${POSTGRES_PASSWORD:-idelibre}
      - TYPEORM_DATABASE=${POSTGRES_DB:-idelibre}
      - TYPEORM_PORT=${POSTGRES_PORT:-5432}
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_LOGGING=false
      - TYPEORM_ENTITIES=src/entity/**/*.ts
      - SALT=${SALT:-saltsaltsalt}
      - LOG_LEVEL=${LOG_LEVEL:-error}
      - PASSPHRASE=${PASSPHRASE:-passphrase}
      - JWT_SECRET=${JWT_SECRET:-jwtsecret}
      - JWT_TIMEOUT=${JWT_TIMEOUT:-86400}
    command: [ "/app/docker-resources/init.sh" ]

    restart: unless-stopped


  nginx-idelibre:
    container_name: nginx-idelibre
    image: nginx:1.23
    depends_on:
      - fpm-idelibre
      - node-idelibre
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/idelibre/dist/docker-resources/nginx.vhost:/etc/nginx/conf.d/default.conf
      - /opt/idelibre/dist/docker-resources/security.conf:/etc/nginx/conf.d/security.conf
      - /opt/idelibre/dist/docker-resources/nginx.conf:/etc/nginx/nginx.conf
      - /opt/idelibre/dist/docker-resources/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
      - data-public:/app/public:ro
      - /data/files:/data:ro
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot


  postgres-idelibre:
    container_name: postgres-idelibre
    image: postgres:16.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-idelibre}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-idelibre}
      - POSTGRES_DB=${POSTGRES_DB:-idelibre}

    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - network_idelibre_dev

    volumes:
      - /data/postgres-docker-idelibre:/var/lib/postgresql/data



  lshorodatage:
    container_name: lshorodatage
    image: registry.libriciel.fr:443/public/citoyens/lshorodatage/lshorodatage:2.0.0
    environment:
      - NODE_ENV=production
      - SITE_HOSTNAME=${URL:-lshorodatage.libriciel.fr}
    volumes:
      - /data/certificates:/certificates
    command: [ "/app/docker-resources/init.sh" ]
    restart: unless-stopped


  ofelia:
    image: mcuadros/ofelia:v0.3.7
    depends_on:
      - fpm-idelibre
    command: daemon --docker
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro


volumes:
  data-public:
  data-file:
