version: '3.8'

services:

  fpm-idelibre_test:
    container_name: fpm-idelibre_test
    build:
      context: .
      dockerfile: DockerfileTest
    env_file:
      - .env.test.docker
    volumes:
      - /tmp/var:/app/var
      - ./.env:/app/.env
      - ./config:/app/config
      - ./src:/app/src
      - ./templates:/app/templates
      - ./migrations:/app/migrations
      - ./vendor:/app/vendor
      - ./public:/app/public
      - ./tests:/app/tests
      - ./phpunit.xml.dist:/app/phpunit.xml.dist
    #command: ["/app/docker-resources/initApp.sh"]
    command: sleep 3000
    networks:
      - network_idelibre_test

networks:
  network_idelibre_test:

