version: '3.4'

services:
  fpm-idelibre:
    container_name: fpm-idelibre
    image: gitlab.libriciel.fr:4567/libriciel/pole-citoyens/idelibre/idelibre:master
    #env_file:
    #  - .env.docker.local
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - VERSION=${VERSION}
      - MAILER_URL=${MAILER_URL}
      - WKHTMLTOPDF_PATH=${WKHTMLTOPDF_PATH}
      - WKHTMLTOIMAGE_PATH=${WKHTMLTOIMAGE_PATH}
      - MAILJET_KEY=${MAILJET_KEY}
      - MAILJET_SECRET=${MAILJET_SECRET}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_ALIAS=${EMAIL_ALIAS}
      - MAILER_TYPE=${MAILER_TYPE}
      - DOCUMENT_MAX_SIZE=${DOCUMENT_MAX_SIZE}
      - DOCUMENT_MAX_COUNT=${DOCUMENT_MAX_COUNT}
      - DOCUMENT_FILES_DIRECTORY=${DOCUMENT_FILES_DIRECTORY}
      - DOCUMENT_ZIP_DIRECTORY=${DOCUMENT_ZIP_DIRECTORY}
      - DOCUMENT_FULL_PDF_DIRECTORY=${DOCUMENT_FULL_PDF_DIRECTORY}
      - TOKEN_DIRECTORY=${TOKEN_DIRECTORY}
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=${PHP_OPCACHE_VALIDATE_TIMESTAMPS}
      - PHP_OPCACHE_MAX_ACCELERATED_FILES=${PHP_OPCACHE_MAX_ACCELERATED_FILES}
      - PHP_OPCACHE_MEMORY_CONSUMPTION=${PHP_OPCACHE_MEMORY_CONSUMPTION}
      - PHP_OPCACHE_MAX_WASTED_PERCENTAGE=${PHP_OPCACHE_MAX_WASTED_PERCENTAGE}
      - SENTRY_DSN=null
    volumes:
      - data-public:/app/public
      - data-file:/tmp
      - ./docker-resources/zz-idelibre.conf:/usr/local/etc/php-fpm.d/zz-idelibre.conf

    command: [ "/app/docker-resources/initApp.sh" ]


  node-idelibre:
    container_name: node-idelibre
    image: gitlab.libriciel.fr:4567/libriciel/pole-citoyens/idelibre/idelibre-nodejs:main
    volumes:
      - data-file:/tmp
    #env_file:
    #  - .env.docker.local
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=${POSTGRES_HOST}
      - TYPEORM_USERNAME=${POSTGRES_USER}
      - TYPEORM_PASSWORD=${POSTGRES_PASSWORD}
      - TYPEORM_DATABASE=${POSTGRES_DB}
      - TYPEORM_PORT=${POSTGRES_PORT}
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_LOGGING=false
      - TYPEORM_ENTITIES=src/entity/**/*.ts
      - SALT=${SALT}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_PATH=${LOG_PATH}
      - LISTEN_PORT=${LISTEN_PORT}
      - PASSPHRASE=${PASSPHRASE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_TIMEOUT=${JWT_TIMEOUT}
      - DOCUMENT_ZIP_DIRECTORY=${DOCUMENT_ZIP_DIRECTORY}
      - DOCUMENT_FULL_PDF_DIRECTORY=${DOCUMENT_FULL_PDF_DIRECTORY}

    command: [ "/app/docker-resources/init.sh" ]


  nginx-idelibre:
    container_name: nginx-idelibre
    image: nginx:1.17
    depends_on:
      - fpm-idelibre
      - node-idelibre
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker-resources/nginx.vhost:/etc/nginx/conf.d/default.conf
      - ./docker-resources/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-resources/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
      - data-public:/app/public:ro

  certbot:
    image: certbot/certbot
    volumes:
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot

  lshorodatage:
    container_name: lshorodatage
    image: gitlab.libriciel.fr:4567/libriciel/pole-citoyens/lshorodatage/lshorodatage:master
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=172.17.0.1
      - POSTGRES_DB=lshorodatage
      - POSTGRES_USER=idelibre
      - POSTGRES_PASSWORD=idelibre
      - POSTGRES_PORT=5432
    command: [ "/app/docker-resources/init.sh" ]

volumes:
  data-public:
  data-file:
