sentry:
  dsn: '%env(SENTRY_DSN)%'
  messenger:
    enabled: true
    capture_soft_fails: true
  options:
    environment: '%kernel.environment%'
    release: '%env(VERSION)%'
    send_default_pii: true
    server_name: '%env(URL)%'
    excluded_exceptions: #exclude validation errors
      - App\Exception\UserNotFoundException
      - Symfony\Component\Security\Core\Exception\AccessDeniedException
  register_error_listener: false
  monolog:
    error_handler:
      enabled: true
      level: error
