sentry:
  register_error_listener: false # Disables the ErrorListener to avoid duplicated log in sentry

monolog:
  handlers:
    sentry:
      type: sentry
      level: !php/const Monolog\Logger::ERROR
      hub_id: Sentry\State\HubInterface
