services:
  App\Service\Connector\ComelusConnectorManager:
    public: true
    autowire: true
    autoconfigure: true

  Libriciel\ComelusApiWrapper\ComelusWrapper:
    public: true
    autowire: true
    autoconfigure: true

  Libriciel\LsMessageWrapper\LsMessageWrapper:
    public: true
    autowire: true
    autoconfigure: true

